name: pytest

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["main"]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install pdm==2.8.2
          pdm export -G test > requirements-all.txt
          pip install -r requirements-all.txt

      - name: Run pytest
        run: pytest
